# Generated by Django 5.2 on 2025-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image_product_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acidity',
            field=models.CharField(default='low', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='Brazil', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.CharField(default='low', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='roast_level',
            field=models.CharField(choices=[('light', 'Светлая'), ('medium', 'Средняя'), ('dark', 'Тёмная')], default='medium', max_length=6),
        ),
    ]
